<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="HasMints.com">

    <link rel="apple-touch-icon" sizes="180x180" href="<?=env('URL'); ?>/assets/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=env('URL'); ?>/assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=env('URL'); ?>/assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?=env('URL'); ?>/assets/favicon/site.webmanifest">

    <title><?=$htmlTitle; ?></title>

    <link href="<?=env('URL'); ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=env('URL'); ?>/assets/css/main.css?t=<?=date('dmYHi'); ?>" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="<?=env('URL'); ?>">SolanaBurnMint</a>
        </div>
    </nav>

    <main>

        <?php if ($alert): ?>
            <div class="container">
                <div class="alert alert-<?=$alert['type']; ?> mt-5 text-center" role="alert">
                    <?=$alert['message']; ?>
                </div>
            </div>
        <?php endif; ?>

        <?=$content; ?>
    </main>

    <footer class="py-4">
        <p>Built by <a target="_blank" href="https://hasmints.com/">HasMints</a>.</p>
    </footer>

    <script src="<?=env('url'); ?>/assets/js/main.js"></script>
</body>

</html>
